permalink: /:categories/:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author:
  name: Cnny
  email: imcnny@gmail.com
  link: http://imcnny.com
  weibo: http://weibo.com/u/2626472453
  github: http://github.com/cnny

# 站点信息
title: 陈康文的博客
description: My personal blog
url: http://imcnny.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: PHP

# 首页除了最新文章外显示分类
cates:
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档